# Usage:
# docker-compose build --build-arg r5version=$(cat build/version.txt)
# docker-compose up 
version: '3'
services:
  r5:
    container_name: r5
    image: local-conveyal-r5:6.4
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "7070:7070"
  ui:
    container_name: ui
    depends_on:
      - mongo
    image: node:12
    ports:
      - "3000:3000"
    links:
      - r5
      - mongo
    volumes:
      - ./analysis-ui:/analysis-ui
    command: bash -c 'cd /analysis-ui && ./run'
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./r5/mongo-data:/data/db:rw

volumes:
  mongo-volume:
