# Usage:
# docker-compose build --build-arg r5version=$(cat build/version.txt)
# docker-compose up 
version: '3'
services:
  r5:
    container_name: r5
    image: local-conveyal-r5:6.4
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "7070:7070"
    # TODO volumes for backend cache directory
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  mongo-volume:
